// Runtime support for code generated by tools/cs2ts. Mirrors the C#/.NET semantics the rule layer relies on.
/* eslint-disable @typescript-eslint/no-explicit-any */

// ------------------------------------------------------------------ external type registry
const impls = new Map<string, any>();
const stubs = new Map<string, any>();

/** Register a hand-written implementation of an external (BCL/Godot/...) type. Wins over generated stubs. */
export function provide(key: string, impl: any) {
  impls.set(key, impl);
  return impl;
}
/** Register a generated stub. */
export function stub(key: string, impl: any) {
  stubs.set(key, impl);
  return impl;
}
const merged = new Set<string>();
/** Hand-written impls fall back to the generated stub for members they do not implement. */
function mergeWithStub(key: string, impl: any, stubv: any) {
  if (merged.has(key) || !impl || !stubv || impl === stubv) return;
  merged.add(key);
  try {
    if (typeof impl === 'function') {
      if (Object.getPrototypeOf(impl) === Function.prototype) Object.setPrototypeOf(impl, stubv);
      if (impl.prototype && Object.getPrototypeOf(impl.prototype) === Object.prototype && stubv.prototype) Object.setPrototypeOf(impl.prototype, stubv.prototype);
    } else if (typeof impl === 'object' && Object.getPrototypeOf(impl) === Object.prototype) {
      Object.setPrototypeOf(impl, stubv);
    }
  } catch {
    /* frozen or exotic object: keep impl as-is */
  }
}
export function ext(key: string): any {
  const im = impls.get(key), st = stubs.get(key);
  if (im !== undefined && st !== undefined) mergeWithStub(key, im, st);
  const v = im ?? st;
  if (v !== undefined) return v;
  const name = key.split(/[.+]/).pop()!.replace(/`\d+$/, '');
  if (/^I[A-Z]/.test(name)) return provide(key, iface(name, [], true));
  return provide(key, missing(key));
}
/** The generated stub class for an external type (to patch behaviour every stub subclass inherits). */
export function stubOf(key: string): any { return stubs.get(key); }
export function extKeys() {
  return { impls: [...impls.keys()], stubs: [...stubs.keys()] };
}

function missing(key: string): any {
  const target = function () {} as any;
  return new Proxy(target, {
    get(t, p) {
      if (p in t) return t[p];
      if (p === 'prototype') return t.prototype;
      if (p === '$fullName') return key;
      if (p === '$name') return key.split(/[.+]/).pop()!.replace(/`\d+$/, '');
      // runtime marker probes ($prim, $iface, $enum, $is, ...) and thenable checks are simply absent
      if (typeof p === 'symbol' || p === 'then' || (typeof p === 'string' && p.startsWith('$'))) return undefined;
      throw new Error(`[rt] external member not implemented: ${key}.${String(p)}`);
    },
    construct() {
      throw new Error(`[rt] external type not implemented: new ${key}()`);
    },
  });
}

// ------------------------------------------------------------------ primitive type markers
function marker(name: string, def: any, prim: string) {
  const f = function () {} as any;
  Object.defineProperties(f, {
    $name: { value: name },
    $fullName: { value: 'System.' + name },
    $default: { value: def },
    $prim: { value: prim },
  });
  return f;
}
export const T = {
  String: marker('String', null, 'string'),
  Boolean: marker('Boolean', false, 'boolean'),
  Int32: marker('Int32', 0, 'number'),
  Int64: marker('Int64', 0, 'number'),
  UInt32: marker('UInt32', 0, 'number'),
  UInt64: marker('UInt64', 0, 'number'),
  Single: marker('Single', 0, 'number'),
  Double: marker('Double', 0, 'number'),
  Decimal: marker('Decimal', 0, 'number'),
  Char: marker('Char', 0, 'number'),
  Byte: marker('Byte', 0, 'number'),
  Object: marker('Object', null, 'object'),
};

// ------------------------------------------------------------------ interfaces & enums
export function iface(name: string, bases: any[], bcl = false): any {
  const f = function () {} as any;
  Object.defineProperties(f, {
    $name: { value: name, writable: true },
    $fullName: { value: name, writable: true },
    $iface: { value: true },
    $bases: { value: bases },
    $bcl: { value: bcl },
    $defaults: { value: null, writable: true },
  });
  return f;
}
export function ifaceDefaults(i: any, cls: any) {
  i.$defaults = cls;
}

export function enumMeta(e: any, name: string, flags: boolean) {
  Object.defineProperties(e, {
    $enum: { value: true },
    $name: { value: name },
    $flags: { value: flags },
  });
}
export function stubEnum(name: string, vals: Record<string, number>) {
  const e: any = {};
  for (const [k, v] of Object.entries(vals)) {
    e[k] = v;
    if (e[v] === undefined) e[v] = k;
  }
  enumMeta(e, name, false);
  return e;
}
export function enumStr(e: any, v: any): string {
  if (v == null) return '';
  const n = e?.[v];
  if (typeof n === 'string') return n;
  if (e?.$flags && typeof v === 'number') {
    if (v === 0) return '0';
    const parts: string[] = [];
    let rest = v;
    for (const k of Object.keys(e)) {
      const bit = e[k];
      if (typeof bit === 'number' && bit !== 0 && (v & bit) === bit && (bit & (bit - 1)) === 0) {
        parts.push(k);
        rest &= ~bit;
      }
    }
    if (rest === 0 && parts.length) return parts.join(', ');
  }
  return String(v);
}
export function enumValues(e: any): number[] {
  return Object.keys(e)
    .filter((k) => typeof e[k] === 'number')
    .map((k) => e[k])
    .filter((v, i, a) => a.indexOf(v) === i);
}
export function hasFlag(a: number, b: number) {
  return (a & b) === b;
}

// ------------------------------------------------------------------ type checks
function ifaceList(ctor: any): any[] {
  const out: any[] = [];
  for (let c = ctor; c && c !== Object && c !== Function.prototype; c = Object.getPrototypeOf(c)) {
    if (Object.hasOwn(c, '$ifaces')) for (const i of c.$ifaces) addIface(i, out);
  }
  return out;
}
function addIface(i: any, out: any[]) {
  if (!i || out.includes(i)) return;
  out.push(i);
  for (const b of i.$bases ?? []) addIface(b, out);
}
const bclIfaceChecks: Record<string, (v: any) => boolean> = {
  IEnumerable: (v) => v != null && (typeof v === 'string' || typeof v[Symbol.iterator] === 'function' || typeof v.GetEnumerator === 'function'),
  IDisposable: (v) => typeof v?.Dispose === 'function',
  IComparable: (v) => typeof v === 'number' || typeof v === 'string' || typeof v?.CompareTo === 'function',
  IList: (v) => Array.isArray(v),
  ICollection: (v) => Array.isArray(v) || v?.Count !== undefined,
  IReadOnlyList: (v) => Array.isArray(v),
  IReadOnlyCollection: (v) => Array.isArray(v) || v?.Count !== undefined,
  IDictionary: (v) => typeof v?.ContainsKey === 'function',
  IReadOnlyDictionary: (v) => typeof v?.ContainsKey === 'function',
  IEquatable: (v) => v != null,
  IConvertible: (v) => typeof v === 'number' || typeof v === 'string' || typeof v === 'boolean',
  IFormattable: (v) => typeof v === 'number',
};
export function isI(v: any, i: any): boolean {
  if (v == null || i == null) return false;
  if (i.$bcl || !i.$iface) {
    const chk = bclIfaceChecks[i.$name];
    if (chk?.(v)) return true; // primitives; classes that declare the interface fall through
  }
  if (typeof v !== 'object' && typeof v !== 'function') return false;
  return ifaceList(v.constructor).includes(i);
}
export function isT(v: any, t: any): boolean {
  if (v == null || t == null) return false;
  if (t.$prim) return t.$prim === 'object' ? true : typeof v === t.$prim;
  if (t.$is) return t.$is(v);
  if (t.$iface) return isI(v, t);
  if (t.$enum) return typeof v === 'number';
  if (t === Array || t.IsArray === true) return Array.isArray(v);
  if (t === String) return typeof v === 'string';
  if (typeof t === 'function') {
    try {
      return v instanceof t;
    } catch {
      return false;
    }
  }
  return false;
}
export function getType(x: any): any {
  if (x == null) throw new (ext('System.NullReferenceException'))('GetType on null');
  switch (typeof x) {
    case 'number':
      return Number.isInteger(x) ? T.Int32 : T.Double;
    case 'string':
      return T.String;
    case 'boolean':
      return T.Boolean;
  }
  return x.constructor;
}
export function defaultOf(t: any): any {
  if (t == null) return null;
  if (t.$default !== undefined) return typeof t.$default === 'function' ? t.$default() : t.$default;
  if (t.$enum) return 0;
  return null;
}
export function create(t: any): any {
  if (t?.$prim) return t.$default;
  if (typeof t?.$new === 'function' && Object.hasOwn(t, '$new')) return t.$new();
  return new t();
}
export function unknownTypeParam(name: string): any {
  return T.Object;
}

// ------------------------------------------------------------------ equality, hashing, comparison
export function equals(a: any, b: any): boolean {
  if (a === b) return true;
  if (a == null || b == null) return false;
  if (typeof a === 'object') {
    const eq = a.Equals;
    if (typeof eq === "function" && eq !== (Object.prototype as any).Equals) return !!eq.call(a, b);
  }
  if (typeof a === 'number' && typeof b === 'number') return Number.isNaN(a) && Number.isNaN(b);
  return false;
}
export function tupleEq(a: any[], b: any[]) {
  if (a === b) return true;
  if (!a || !b || a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (!equals(a[i], b[i])) return false;
  return true;
}
let idCounter = 1;
const ids = new WeakMap<object, number>();
export function idHash(o: any): number {
  if (o == null) return 0;
  if (typeof o !== 'object' && typeof o !== 'function') return hash(o);
  let v = ids.get(o);
  if (v === undefined) ids.set(o, (v = idCounter++));
  return v;
}
export function strHash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (Math.imul(h, 31) + s.charCodeAt(i)) | 0;
  return h;
}
export function hash(x: any): number {
  if (x == null) return 0;
  switch (typeof x) {
    case 'number':
      return Number.isInteger(x) ? x | 0 : strHash(String(x));
    case 'string':
      return strHash(x);
    case 'boolean':
      return x ? 1 : 0;
  }
  if (Array.isArray(x)) return hashCombine(...x);
  return typeof x.GetHashCode === 'function' ? x.GetHashCode() | 0 : idHash(x);
}
export function hashCombine(...vals: any[]): number {
  let h = 17;
  for (const v of vals) h = (Math.imul(h, 31) + hash(v)) | 0;
  return h;
}
/** Normalized map key honoring C# value equality (records, tuples, primitives). */
export function keyOf(k: any): any {
  if (k === null || k === undefined) return k;
  const t = typeof k;
  if (t !== 'object') return t === 'number' && Object.is(k, -0) ? 0 : k;
  if (Array.isArray(k)) return '\u0001[' + k.map((x) => { const n = keyOf(x); return typeof n === 'object' ? 'o' + idHash(n) : typeof n + ':' + String(n); }).join(',') + ']';
  if (typeof k.$key === 'function') return '\u0001k' + k.$key();
  return k;
}
// Comparer<string>.Default / string.CompareTo are culture-sensitive (ICU; the game never sets a culture, and IDs are
// ASCII, where every locale sorts like the root collation: "_" before digits before letters, "a" before "A").
// ModelDb.AllRelics/AllPotions are ordered this way, so ordinal order would change seeded picks.
const collator = new Intl.Collator('en-US');
const collatorIgnoreCase = new Intl.Collator('en-US', { sensitivity: 'accent' });
export const compareOrdinal = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);
/** string.Compare(a, b, StringComparison | ignoreCase). */
export function compareStr(a: string | null, b: string | null, c?: number | boolean): number {
  if (a == null || b == null) return a == null ? (b == null ? 0 : -1) : 1;
  if (c === 4) return compareOrdinal(a, b);
  if (c === 5) return compareOrdinal(a.toUpperCase(), b.toUpperCase());
  const r = (c === true || c === 1 || c === 3 ? collatorIgnoreCase : collator).compare(a, b);
  return r < 0 ? -1 : r > 0 ? 1 : 0;
}
/** IList<T>/IReadOnlyList<T> indexer: arrays directly, other implementations through get_Item. */
export const at = (r: any, i: number) => (Array.isArray(r) || typeof r === 'string' ? r[i] : r.get_Item(i));
/** `v is T[]` / `v is List<T>`: arrays carry no element type, so check the first element (C# collections are homogeneous). */
export const isArrOf = (v: any, el: (x: any) => boolean) => Array.isArray(v) && (v.length === 0 || v[0] == null || el(v[0]));
/**
 * The Type of `T[]` / `List<T>` in reflection metadata ($members): arrays erase their element type at runtime, but
 * SavedProperties needs PropertyType.GetElementType() to restore int / enum arrays.
 */
const arrayTypes = new Map<any, any>();
export function arrayOf(elem: any): any {
  let t = arrayTypes.get(elem);
  if (!t) {
    t = function Array() {};
    Object.defineProperties(t, { GetElementType: { value: () => elem ?? null }, IsArray: { value: true } });
    arrayTypes.set(elem, t);
  }
  return t;
}
export function compare(a: any, b: any): number {
  if (a === b) return 0;
  if (a == null) return -1;
  if (b == null) return 1;
  if (typeof a === 'number' && typeof b === 'number') return a < b ? -1 : a > b ? 1 : 0;
  if (typeof a === 'string' && typeof b === 'string') return compareStr(a, b);
  if (typeof a === 'boolean') return (a ? 1 : 0) - (b ? 1 : 0);
  if (Array.isArray(a) && Array.isArray(b)) {
    for (let i = 0; i < Math.min(a.length, b.length); i++) {
      const c = compare(a[i], b[i]);
      if (c) return c;
    }
    return a.length - b.length;
  }
  if (typeof a.CompareTo === 'function') return a.CompareTo(b);
  throw new (ext('System.InvalidOperationException'))('Failed to compare two elements');
}
export function comparer(c: any): (a: any, b: any) => number {
  if (c == null) return compare;
  if (typeof c === 'function') return c;
  if (typeof c.Compare === 'function') return (a, b) => c.Compare(a, b);
  return compare;
}

// ------------------------------------------------------------------ numbers
/** C# decimal arithmetic emulated on doubles: round away binary noise. */
export function dm(x: number): number {
  if (!Number.isFinite(x)) return x;
  const r = Math.round(x * 1e9) / 1e9;
  return Object.is(r, -0) ? 0 : r;
}
export function idiv(a: number, b: number): number {
  if (b === 0) throw new (ext('System.DivideByZeroException'))('Attempted to divide by zero.');
  return Math.trunc(a / b);
}
export const trunc = Math.trunc;
/** .NET Math.Round semantics (default MidpointRounding.ToEven). mode: 0 ToEven, 1 AwayFromZero, 2 ToZero, 3 ToNegInf, 4 ToPosInf */
export function round(x: number, digits = 0, mode = 0): number {
  const p = Math.pow(10, digits);
  const v = dm(x * p);
  let r: number;
  switch (mode) {
    case 1: r = Math.sign(v) * Math.round(Math.abs(v)); break;
    case 2: r = Math.trunc(v); break;
    case 3: r = Math.floor(v); break;
    case 4: r = Math.ceil(v); break;
    default: {
      const f = Math.floor(v);
      const diff = v - f;
      if (diff > 0.5) r = f + 1;
      else if (diff < 0.5) r = f;
      else r = f % 2 === 0 ? f : f + 1;
    }
  }
  return digits ? r / p : r;
}

// ------------------------------------------------------------------ strings & formatting
export function str(x: any): string {
  if (x == null) return '';
  switch (typeof x) {
    case 'string': return x;
    case 'boolean': return x ? 'True' : 'False';
    case 'number': return numStr(x);
    case 'function': return x.$fullName ?? x.name;
  }
  if (typeof x.ToString === 'function') return String(x.ToString());
  return String(x);
}
export function numStr(x: number): string {
  if (Number.isNaN(x)) return 'NaN';
  if (x === Infinity) return '∞';
  if (x === -Infinity) return '-∞';
  const s = String(x);
  return s.includes('e') ? s.replace('e', 'E').replace('E+', 'E+').replace(/E(\d)/, 'E+$1') : s;
}
function groupThousands(intPart: string) {
  return intPart.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}
function fixed(x: number, n: number) {
  return round(x, n, 1).toFixed(n);
}
export function fmt(x: any, format: string | null, align = 0): string {
  if (typeof format !== 'string') format = null;
  let s: string;
  if (format == null || format === '') s = str(x);
  else if (typeof x === 'number') s = fmtNum(x, format);
  else if (x != null && typeof x.ToString === 'function' && x.ToString.length > 0) s = String(x.ToString(format));
  else s = str(x);
  if (align > 0) s = s.padStart(align);
  else if (align < 0) s = s.padEnd(-align);
  return s;
}
export function fmtNum(x: number, format: string): string {
  const m = /^([A-Za-z])(\d*)$/.exec(format);
  if (m) {
    const c = m[1].toUpperCase();
    const n = m[2] === '' ? undefined : parseInt(m[2], 10);
    switch (c) {
      case 'F': return fixed(x, n ?? 2);
      case 'N': { const f = fixed(Math.abs(x), n ?? 2); const [i, d] = f.split('.'); return (x < 0 ? '-' : '') + groupThousands(i) + (d ? '.' + d : ''); }
      case 'D': { const t = Math.trunc(Math.abs(x)).toString().padStart(n ?? 0, '0'); return (x < 0 ? '-' : '') + t; }
      case 'P': return fixed(x * 100, n ?? 2) + '%';
      case 'X': { const t = (x >>> 0).toString(16).toUpperCase(); return t.padStart(n ?? 0, '0'); }
      case 'G': case 'R': return n ? String(Number(x.toPrecision(n))) : numStr(x);
      case 'E': return x.toExponential(n ?? 6).toUpperCase().replace(/E([+-])(\d)$/, 'E$100$2').replace(/E([+-])(\d\d)$/, 'E$10$2');
    }
  }
  return fmtCustom(x, format);
}
function fmtCustom(x: number, format: string): string {
  const sections = format.split(';');
  let f = sections[0];
  let v = x;
  if (sections.length > 1 && x < 0) { f = sections[1]; v = -x; }
  else if (sections.length > 2 && x === 0) f = sections[2];
  const percent = f.includes('%');
  if (percent) v *= 100;
  const lit = (s: string) => s.replace(/['"]/g, '');
  const m = /^([^0#.,]*)([0#,]*)(?:\.([0#]*))?(.*)$/.exec(f);
  if (!m) return str(x);
  const [, pre, intPat, decPat = '', post] = m;
  const minDec = (decPat.match(/0/g) ?? []).length;
  const maxDec = decPat.length;
  let s = round(Math.abs(v), maxDec, 1).toFixed(maxDec);
  if (maxDec > minDec) s = s.replace(new RegExp(`0{0,${maxDec - minDec}}$`), '').replace(/\.$/, '');
  let [ip, dp] = s.split('.');
  const minInt = (intPat.match(/0/g) ?? []).length;
  ip = ip.padStart(minInt, '0');
  if (minInt === 0 && ip === '0' && intPat.length > 0 && !intPat.includes('0')) ip = dp ? '' : '0';
  if (intPat.includes(',')) ip = groupThousands(ip);
  const neg = v < 0 && sections.length === 1 && (ip !== '0' || (dp && /[1-9]/.test(dp)));
  return (neg ? '-' : '') + lit(pre) + ip + (dp ? '.' + dp : '') + lit(post);
}
export function chars(s: string): Iterable<number> {
  return {
    *[Symbol.iterator]() {
      for (let i = 0; i < s.length; i++) yield s.charCodeAt(i);
    },
  };
}
export function cs(x: any): string {
  return typeof x === 'number' ? String.fromCharCode(x) : x;
}
export function newString(a: any, count?: number): string {
  if (typeof a === 'number') return String.fromCharCode(a).repeat(count ?? 1);
  if (Array.isArray(a)) return charsToStr(a);
  return String(a);
}

// ------------------------------------------------------------------ arrays & iteration
export function newArr(n: number, def: any): any[] {
  const a = new Array(n);
  for (let i = 0; i < n; i++) a[i] = def;
  return a;
}
export function newArrF(n: number, f: () => any): any[] {
  const a = new Array(n);
  for (let i = 0; i < n; i++) a[i] = f();
  return a;
}
export function newArr2(w: number, h: number, def: any): any[][] {
  const a = new Array(w);
  for (let i = 0; i < w; i++) a[i] = newArr(h, def);
  return a;
}
export function iter(x: any): Iterable<any> {
  if (x == null) throw new (ext('System.NullReferenceException'))('Object reference not set to an instance of an object (enumerating null).');
  if (typeof x === 'string') return chars(x);
  if (typeof x[Symbol.iterator] === 'function') return x;
  if (typeof x.GetEnumerator === 'function') return enumeratorIterable(x);
  throw new (ext('System.InvalidOperationException'))('object is not enumerable');
}
function enumeratorIterable(x: any): Iterable<any> {
  return {
    [Symbol.iterator]() {
      const e = x.GetEnumerator();
      if (typeof e?.next === 'function') return e;
      if (e && typeof e[Symbol.iterator] === 'function') return e[Symbol.iterator]();
      return {
        next() {
          if (e.MoveNext()) return { value: e.Current, done: false };
          e.Dispose?.();
          return { value: undefined, done: true };
        },
      } as Iterator<any>;
    },
  };
}
export function makeIterable(cls: any) {
  if (Object.hasOwn(cls.prototype, Symbol.iterator)) return;
  Object.defineProperty(cls.prototype, Symbol.iterator, {
    value: function (this: any) {
      return enumeratorIterable(this)[Symbol.iterator]();
    },
    configurable: true,
  });
}
export function toArray(x: any): any[] {
  return Array.from(iter(x));
}
/** A C# IEnumerator over a JS iterator. */
export class Enumerator {
  private it: Iterator<any>;
  Current: any = undefined;
  constructor(src: Iterable<any>) {
    this.it = src[Symbol.iterator]();
  }
  MoveNext() {
    const r = this.it.next();
    if (r.done) return false;
    this.Current = r.value;
    return true;
  }
  Dispose() {
    this.it.return?.();
  }
  Reset() {}
  [Symbol.iterator]() {
    return this.it;
  }
}

// ------------------------------------------------------------------ delegates
export function dcombine(a: any, b: any): any {
  if (!a) return b ?? null;
  if (!b) return a;
  const list = [...(a.$list ?? [a]), ...(b.$list ?? [b])];
  return multicast(list);
}
export function dremove(a: any, b: any): any {
  if (!a || !b) return a ?? null;
  const list: any[] = [...(a.$list ?? [a])];
  const rm: any[] = b.$list ?? [b];
  for (let i = list.length - rm.length; i >= 0; i--) {
    if (rm.every((f, j) => f === list[i + j])) {
      list.splice(i, rm.length);
      break;
    }
  }
  return list.length === 0 ? null : list.length === 1 ? list[0] : multicast(list);
}
function multicast(list: any[]) {
  const f: any = (...args: any[]) => {
    let r;
    for (const fn of list) r = fn(...args);
    return r;
  };
  f.$list = list;
  return f;
}
const bound = new WeakMap<object, Map<any, any>>();
export function bindFn(obj: any, fn: any): any {
  if (fn == null) return null;
  if (obj == null || (typeof obj !== 'object' && typeof obj !== 'function')) return fn.bind(obj);
  let m = bound.get(obj);
  if (!m) bound.set(obj, (m = new Map()));
  let b = m.get(fn);
  if (!b) m.set(fn, (b = fn.bind(obj)));
  return b;
}

// ------------------------------------------------------------------ classes
export function superGet(proto: any, name: string, self: any) {
  return Reflect.get(proto, name, self);
}
export function superSet(proto: any, name: string, self: any, v: any) {
  Reflect.set(proto, name, v, self);
}
export function extBase(self: any, base: any, args: any[]) {
  if (typeof base?.$extCtor === 'function') base.$extCtor.call(self, ...args);
}
export const discard = undefined;
export function throw_(e: any): never {
  throw e;
}
export function throwSwitch(v?: any): never {
  throw new (ext('System.Runtime.CompilerServices.SwitchExpressionException'))(`Non-exhaustive switch expression: ${str(v)}`);
}
export function rethrowMissing(): never {
  throw new Error('rethrow outside catch');
}
export function fromEnd(n: number) {
  return { $fromEnd: n };
}
export function isEx(e: any, t: any): boolean {
  if (e instanceof t) return true;
  if (e instanceof TypeError && t?.$name === 'NullReferenceException') return true;
  if (!(e instanceof Error)) return false;
  return t?.$name === 'Exception' || t === Error;
}
const regexCache = new Map<string, any>();
export function regex(pattern: string, options: number) {
  const k = options + ':' + pattern;
  let r = regexCache.get(k);
  if (!r) regexCache.set(k, (r = new (ext('System.Text.RegularExpressions.Regex'))(pattern, options)));
  return r;
}
export function cctor(cls: any) {
  try {
    cls.$cctor();
  } catch (e) {
    console.warn(`[rt] static constructor of ${cls.$name} failed:`, (e as Error)?.message ?? e);
  }
}
export const types = new Map<string, any>();
export function registerTypes(all: Record<string, any>) {
  for (const t of Object.values(all)) {
    types.set(t.$fullName, t);
    applyIfaceDefaults(t);
  }
}
function applyIfaceDefaults(t: any) {
  for (const i of ifaceList(t)) {
    const d = i.$defaults;
    if (!d) continue;
    for (const k of Object.getOwnPropertyNames(d.prototype)) {
      if (k === 'constructor' || k in t.prototype) continue;
      Object.defineProperty(t.prototype, k, Object.getOwnPropertyDescriptor(d.prototype, k)!);
    }
  }
}

/** C# lifted operator on nullable value types: null if either operand is null. */
export function lift2(a: any, b: any, f: (a: any, b: any) => any, whenNull: any) {
  return a == null || b == null ? whenNull : f(a, b);
}
/** Lifted user-defined ==: null == null, null != value. */
export function liftEq(a: any, b: any, eq: (a: any, b: any) => boolean) {
  return a == null || b == null ? a == null && b == null : eq(a, b);
}
export function tupleStr(t: any[]) {
  return '(' + t.map(str).join(', ') + ')';
}
/** 64-bit shifts and bitwise ops (C# long/ulong); JS bit operators are 32-bit. */
export function op64(op: string, a: number, b: number): number {
  switch (op) {
    case '<<': return a * 2 ** (b & 63);
    case '>>': case '>>>': return Math.floor(a / 2 ** (b & 63));
  }
  const x = BigInt.asUintN(64, BigInt(Math.trunc(a))), y = BigInt.asUintN(64, BigInt(Math.trunc(b)));
  const r = op === '&' ? x & y : op === '|' ? x | y : x ^ y;
  return Number(r);
}
/** C# interface static members live on the interface marker object. */
export function ifaceStatics(i: any, cls: any) {
  for (const [k, d] of Object.entries(Object.getOwnPropertyDescriptors(cls))) {
    if (k === 'prototype' || k === 'name' || k === 'length') continue;
    Object.defineProperty(i, k, d);
  }
}
/** Inert instance of a generated scene-node stub (every member returns a neutral default). */
/**
 * Span<T>/ReadOnlySpan<T> over an array: a live view (writes through `Slice(...)` land in the backing array, as the
 * compiler's collection-expression lowering `a.CopyTo(new Span<T>(dest).Slice(i, n))` relies on). Indexable via Proxy.
 * String-backed char spans stay plain strings.
 */
export class SpanView<T = any> {
  constructor(public $a: T[], public $o = 0, public $n = $a.length - $o) {}
  get length() { return this.$n; }
  get Length() { return this.$n; }
  get IsEmpty() { return this.$n === 0; }
  Slice(o: number, n = this.$n - o) { return span(this.$a, this.$o + o, n); }
  CopyTo(dst: any) {
    const d = dst instanceof SpanView ? dst : (dst?.$view as SpanView) ?? new SpanView(dst);
    for (let i = 0; i < this.$n; i++) d.$a[d.$o + i] = this.$a[this.$o + i];
  }
  Fill(v: T) { for (let i = 0; i < this.$n; i++) this.$a[this.$o + i] = v; }
  Clear() { this.Fill(null as any); }
  ToArray() { return this.$a.slice(this.$o, this.$o + this.$n); }
  IndexOf(v: T) { for (let i = 0; i < this.$n; i++) if (equals(this.$a[this.$o + i], v)) return i; return -1; }
  Contains(v: T) { return this.IndexOf(v) >= 0; }
  *[Symbol.iterator]() { for (let i = 0; i < this.$n; i++) yield this.$a[this.$o + i]; }
  GetEnumerator() { return new Enumerator(this[Symbol.iterator]()); }
}
export function span(a: any, o = 0, n?: number): any {
  if (a == null) return new SpanView([]);
  if (typeof a === 'string') return n === undefined ? a.slice(o) : a.substr(o, n);
  const v = new SpanView(a, o, n ?? a.length - o);
  return new Proxy(v, {
    get(t, p, r) {
      if (p === '$view') return t;
      if (typeof p === 'string' && /^\d+$/.test(p)) return t.$a[t.$o + +p];
      return Reflect.get(t, p, r);
    },
    set(t, p, val) {
      if (typeof p === 'string' && /^\d+$/.test(p)) { t.$a[t.$o + +p] = val; return true; }
      return Reflect.set(t, p, val);
    },
  });
}
/** String.fromCharCode over an array without spreading it (large arrays overflow the call stack). */
export function charsToStr(a: ArrayLike<number>): string {
  let out = '';
  for (let i = 0; i < a.length; i += 8192) out += String.fromCharCode.apply(null, Array.prototype.slice.call(a, i, i + 8192) as number[]);
  return out;
}
/** Char spans: string-backed or char-code-array-backed. */
export function chAt(s: any, i: number): number { return typeof s === 'string' ? s.charCodeAt(i) : s[i]; }
export function spanStr(s: any): string { return typeof s === 'string' ? s : charsToStr(s); }
export function dummy(cls: any) {
  try { return new cls(); } catch { return null; }
}
/** Static node factories (NCard.Create, NVfx.Create, ...) return null under TestMode, like the originals; otherwise an inert stub. */
export const headless = { on: false };
export function sdummy(cls: any) { return headless.on ? null : dummy(cls); }
