using System.Text;
using Microsoft.CodeAnalysis;

/// Stub classes for every non-BCL external type the rule layer touches (Godot, excluded Nodes, SmartFormat, ...).
/// Each stub member returns a neutral default; the runtime and render layer overwrite what they implement.
public static class Stubs
{
    public static string Generate(Ctx ctx, Emitter em)
    {
        var sb = new StringBuilder("// @ts-nocheck\n// Generated by tools/cs2ts. Stubs for external types referenced by the rule layer.\nimport * as $ from \"../rt/index\";\n\n");
        var types = ctx.ExtAliases.Keys.Where(t => !Ctx.IsBcl(t)).ToList();
        int Depth(INamedTypeSymbol t) { int d = 0; for (var b = t.BaseType; b != null && ctx.ExtAliases.ContainsKey(b.OriginalDefinition) && !Ctx.IsBcl(b); b = b.BaseType) d++; return d; }
        foreach (var t in types.OrderBy(Depth).ThenBy(t => Ctx.TypeKey(t), StringComparer.Ordinal))
        {
            var alias = ctx.ExtAliases[t];
            var key = Ctx.TypeKey(t);
            if (t.TypeKind == TypeKind.Enum)
            {
                var vals = t.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue).Select(f => $"{Ctx.CleanName(f.Name)}: {Convert.ToInt64(f.ConstantValue)}");
                sb.Append($"$.stub({Emitter.Q(key)}, $.stubEnum({Emitter.Q(t.Name)}, {{ {string.Join(", ", vals)} }}));\n");
                continue;
            }
            if (t.TypeKind == TypeKind.Interface) { sb.Append($"$.stub({Emitter.Q(key)}, $.iface({Emitter.Q(t.Name)}, []));\n"); continue; }
            if (t.TypeKind == TypeKind.Delegate) continue;
            bool isJsonCtx = false;
            for (var b = t.BaseType; b != null; b = b.BaseType) if (b.Name == "JsonSerializerContext") isJsonCtx = true;
            if (isJsonCtx)
            {
                sb.Append($"export class {alias} {{ static $name = {Emitter.Q(t.Name)}; static get Default() {{ return $.jsonContext({Emitter.Q(t.Name)}); }} }}\n$.stub({Emitter.Q(key)}, {alias});\n");
                continue;
            }
            var bt = t.BaseType;
            var ext = bt != null && !Ctx.IsBcl(bt) && ctx.ExtAliases.ContainsKey(bt.OriginalDefinition) ? $" extends {ctx.ExtAliases[bt.OriginalDefinition]}" : "";
            var body = new StringBuilder();
            body.Append($"static $name = {Emitter.Q(t.Name)};\nstatic $fullName = {Emitter.Q(key)};\nstatic $stub = true;\n");
            if (t.IsValueType) body.Append($"static $default() {{ return new {alias}(); }}\n");
            var uses = ctx.ExtUses.TryGetValue(t, out var u) ? u : new HashSet<ISymbol>();
            var done = new HashSet<string>();
            foreach (var m in uses.OrderBy(m => m.Name, StringComparer.Ordinal))
            {
                var st = m.IsStatic ? "static " : "";
                switch (m)
                {
                    case IMethodSymbol ms when ms.MethodKind is MethodKind.Ordinary or MethodKind.UserDefinedOperator or MethodKind.Conversion:
                        {
                            var n = ctx.MethodName(ms);
                            if (!done.Add(st + n)) break;
                            // Generic methods receive their type arguments first: `GetSpecialNode<Node2D>(path)` → (Node2D$, path).
                            var tp = ms.ReturnType as ITypeParameterSymbol;
                            var d = tp is { TypeParameterKind: TypeParameterKind.Method } ? (tp.ConstraintTypes.Any(c => IsNode(c)) && !ms.IsStatic ? $"$.dummy(a[{tp.Ordinal}])" : $"$.defaultOf(a[{tp.Ordinal}])")
                                : DummyAlias(ctx, ms.ReturnType) is { } da ? (!ms.IsStatic ? $"$.dummy({da})" : ms.Name.StartsWith("Create") ? $"$.sdummy({da})" : "null") : Def(ctx, em, ms.ReturnType);
                            // Unmangled overloads share one JS function (GetNode(path) / GetNode<T>(path)); if any overload
                            // returns its type parameter, a type argument passed first selects a dummy of that type.
                            var genericSibling = !ms.IsStatic && uses.OfType<IMethodSymbol>().Any(o => o.Name == ms.Name && ctx.MethodName(o) == n
                                && o.ReturnType is ITypeParameterSymbol { TypeParameterKind: TypeParameterKind.Method });
                            if (genericSibling) d = $"(typeof a[0] === \"function\" && a[0].$name ? $.dummy(a[0]) : {d})";
                            body.Append($"{st}{n}(...a) {{ return {d}; }}\n");
                            break;
                        }
                    case IPropertySymbol { IsIndexer: true } ip:
                        if (done.Add("get_Item")) body.Append($"get_Item(...a) {{ return {Def(ctx, em, ip.Type)}; }}\nset_Item(...a) {{ return a[a.length - 1]; }}\n");
                        break;
                    case IPropertySymbol or IFieldSymbol or IEventSymbol:
                        {
                            var n = Ctx.CleanName(m.Name);
                            if (!done.Add(st + n)) break;
                            var type = m switch { IPropertySymbol p => p.Type, IFieldSymbol f => f.Type, IEventSymbol e => e.Type, _ => null };
                            if (m is IFieldSymbol { HasConstantValue: true } cf) { body.Append($"static {n} = {em.ConstLit(cf.ConstantValue, cf.Type)};\n"); break; }
                            var d = type != null && type.Name == "StringName" && m.IsStatic ? Emitter.Q(m.Name) : Def(ctx, em, type);
                            if (!m.IsStatic && type != null && DummyAlias(ctx, type) is { } da) d = $"(this.$_{n} = $.dummy({da}))";
                            if (m is IEventSymbol) d = "null";
                            var holder = m.IsStatic ? alias : "this";
                            body.Append($"{st}get {n}() {{ return {holder}.$_{n} !== undefined ? {holder}.$_{n} : {d}; }}\n{st}set {n}(v) {{ {holder}.$_{n} = v; }}\n");
                            break;
                        }
                }
            }
            sb.Append($"export class {alias}{ext} {{\n{Emitter.Indent(body.ToString())}}}\n$.stub({Emitter.Q(key)}, {alias});\n");
        }
        return sb.ToString();
    }

    /// Members (and static factories) returning scene-node types yield inert stub instances, so `Instance.Ui.Hand.Foo()` chains are safe no-ops.
    static string? DummyAlias(Ctx ctx, ITypeSymbol t)
    {
        if (t is not INamedTypeSymbol n || n.TypeKind != TypeKind.Class || Ctx.IsBcl(n) || ctx.IsIncluded(n)) return null;
        bool node = false;
        for (var b = n; b != null; b = b.BaseType) if (b.Name == "GodotObject") node = true;
        // the excluded Spine/Godot wrapper layer (MegaSprite, MegaAnimationState, ...) is just as inert
        if ((n.ContainingNamespace?.ToDisplayString() ?? "").StartsWith("MegaCrit.Sts2.Core.Bindings")) node = true;
        if (!node) return null;
        // Types only reached through a member's type (NDrawPileButton) have no stub; use the nearest stubbed base.
        for (var b = n; b != null; b = b.BaseType) if (ctx.ExtAliases.TryGetValue(b.OriginalDefinition, out var a)) return a;
        return null;
    }

    static bool IsNode(ITypeSymbol t) { for (var b = t as INamedTypeSymbol; b != null; b = b.BaseType) if (b.Name == "GodotObject") return true; return false; }

    static string Def(Ctx ctx, Emitter em, ITypeSymbol? t)
    {
        if (t == null || t is ITypeParameterSymbol) return "null";
        if (t.SpecialType == SpecialType.System_Void) return "undefined";
        var key = t is INamedTypeSymbol n ? Ctx.TypeKey(n) : "";
        if (key == "System.Threading.Tasks.Task") return "$.Task.CompletedTask";
        if (key == "System.Threading.Tasks.Task`1") return $"$.Task.FromResult({em.DefaultOf(((INamedTypeSymbol)t).TypeArguments[0])})";
        if (t.SpecialType == SpecialType.System_String) return "\"\"";
        if (t is IArrayTypeSymbol || Ctx.IsArrayLike(t) || key is "System.Collections.Generic.IEnumerable`1" or "System.Collections.IEnumerable") return "[]";
        // inert nodes have no children/metadata: Godot collections come back empty, never null
        if (key is "Godot.Collections.Array" or "Godot.Collections.Array`1") return "[]";
        if (key is "Godot.Collections.Dictionary" or "Godot.Collections.Dictionary`2") return "new $.Dictionary()";
        if (t.IsValueType && t is INamedTypeSymbol nt && !ctx.IsIncluded(nt) && !Ctx.IsBcl(nt) && nt.TypeKind == TypeKind.Struct)
            return ctx.ExtAliases.TryGetValue(nt.OriginalDefinition, out var sa) ? $"$.defaultOf({sa})" : "null";
        return em.DefaultOf(t);
    }
}
